[package]
name = "scraps"
authors = ["boykush <k.taichi0315@gmail.com>"]
version = "0.9.4"
edition = "2021"
license = "MIT"
description = "A static site generator that builds a wiki from a set of markdown files. Inspired by https://scrapbox.io/."
homepage = "https://boykush.github.io/scraps"
repository = "https://github.com/boykush/scraps"
readme = "README.md"
exclude = [
    "scraps/",
    ".github/",
    "Dockerfile"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
serde = { version = "1.0.190", features = ["derive"] }
anyhow = "1.0.75"
config = { version = "0.13.3", features = ["toml"] }
tera = "1.19.1"
thiserror = "1.0.50"
once_cell = "1.18.0"
pulldown-cmark = "0.9.3"
itertools = "0.11.0"
url = { version = "2.4.1", features = ["serde"] }
chrono-tz = { version = "0.8.3", features = ["serde"] }
colored = "2.0.4"
