[workspace]
[workspace.package]
edition = "2021"
authors = ["boykush <boykush315@gmail.com>"]
license = "MIT"
version = "0.15.5"
description = "A static site generator that builds a wiki from a set of markdown files."
homepage = "https://boykush.github.io/scraps"
repository = "https://github.com/boykush/scraps"
documentation = "https://boykush.github.io/scraps"
rust-version = "1.83"
[workspace.dependencies]
scraps_libs = { version = "0.15.5", path = "modules/libs" }

[package]
edition.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
rust-version.workspace = true
name = "scraps"
readme = "README.md"
exclude = [
    "scraps/",
    ".github/",
    "Dockerfile",
    "assets/"
]
[dependencies]
# sub crates
scraps_libs.workspace = true

# external crates
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
config = { version = "0.15", features = ["toml"] }
tera = "1.20"
thiserror = "2.0"
once_cell = "1.20"
pulldown-cmark = "0.12"
itertools = "0.13"
url = { version = "2.5", features = ["serde"] }
chrono-tz = { version = "0.10", features = ["serde"] }
colored = "2.2"
hyper = { version = "1.5", features = ["full"] }
tokio = { version = "1.42", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
percent-encoding = "2.3"